#!/usr/bin/env node
/**
 * Ria Art Jewellery — CMS Build Script
 *
 * Reads individual JSON files from assets/data/products/, collections/, occasions/
 * and aggregates them into:
 *   - assets/data/products.json  (consumed by search.js)
 *   - assets/js/products-data.js (window.RIA_PRODUCTS — synchronous, consumed by collection-page.js, filters.js, etc.)
 *   - assets/data/categories.json
 *   - assets/data/occasions.json
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PRODUCTS_DIR = path.join(ROOT, 'assets', 'data', 'products');
const COLLECTIONS_DIR = path.join(ROOT, 'assets', 'data', 'collections');
const OCCASIONS_DIR = path.join(ROOT, 'assets', 'data', 'occasions');

// ─── helpers ──────────────────────────────────────────────────────────────────

function readJsonDir(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); }
      catch (e) { console.warn(`Skipping ${f}: ${e.message}`); return null; }
    })
    .filter(Boolean);
}

// Convert long-form pricing_type (from CMS/products.json) to short form used by products-data.js
function shortPricingType(long) {
  const map = {
    'Single Price':        'single',
    'SGM Finish Variants': 'sgm',
    'Quantity Variants':   'quantity',
    'Colour Variants':     'colour',
  };
  return map[long] || long;
}

// Convert absolute image path to relative path expected by products-data.js
// /assets/images/products/bangles/foo.jpeg → bangles/foo.jpeg
function toRelativeImg(abs) {
  if (!abs) return '';
  const prefix = '/assets/images/products/';
  if (abs.startsWith(prefix)) return abs.slice(prefix.length);
  return abs;
}

// ─── 1. Build products.json (long-form — used by search.js) ──────────────────

const products = readJsonDir(PRODUCTS_DIR)
  .filter(p => p.published !== false)
  .sort((a, b) => (a.title || '').localeCompare(b.title || ''));

const productsJsonPath = path.join(ROOT, 'assets', 'data', 'products.json');
fs.writeFileSync(productsJsonPath, JSON.stringify(products, null, 2), 'utf8');
console.log(`✓ products.json — ${products.length} products`);

// ─── 2. Build products-data.js (short-form — used by collection-page.js) ─────

function buildProductEntry(p) {
  const type = shortPricingType(p.pricing_type);
  const imgs = (p.images || []).map(toRelativeImg);

  const entry = {
    id:          p.slug,
    slug:        p.slug,
    title:       p.title,
    category:    p.category,
    category_slug: p.category_slug || p.category.toLowerCase().replace(/\s+/g, '-'),
    occasions:   p.occasions   || [],
    style:       p.style       || [],
    metal:       p.metal       || '',
    price_band:  p.price_band  || '',
    availability: p.availability || 'In Stock',
    featured:    !!p.featured,
    bestseller:  !!p.bestseller,
    new_arrival: !!p.new_arrival,
    has_bead_guarantee: !!p.has_bead_guarantee,
    images:      imgs,
    pricing_type: type,
  };

  if (type === 'single') {
    entry.price = p.price || 0;
  } else if (type === 'sgm') {
    entry.sgm_price = p.sgm_price || 0;
  } else if (type === 'quantity') {
    entry.quantity_variants = (p.quantity_variants || []).map(v => ({
      label: v.label, price: v.price
    }));
  } else if (type === 'colour') {
    entry.colour_variants = (p.colour_variants || []).map(v => ({
      label: v.label, price: v.price, image: toRelativeImg(v.image || '')
    }));
  }

  return entry;
}

const productEntries = products.map(buildProductEntry);

const productsDataJs = `/* AUTO-GENERATED by scripts/build.js — do not edit manually */
window.RIA_PRODUCTS = ${JSON.stringify(productEntries, null, 2)};

window.RIA_FORMAT_PRICE = function(n) {
  return '₹' + Number(n).toLocaleString('en-IN');
};

window.RIA_IMG = function(rel) {
  if (!rel) return '';
  if (rel.startsWith('/') || rel.startsWith('http')) return rel;
  return '/assets/images/products/' + rel;
};
`;

const productsDataJsPath = path.join(ROOT, 'assets', 'js', 'products-data.js');
fs.writeFileSync(productsDataJsPath, productsDataJs, 'utf8');
console.log(`✓ products-data.js — ${productEntries.length} products`);

// ─── 3. Build categories.json ─────────────────────────────────────────────────

const collections = readJsonDir(COLLECTIONS_DIR)
  .filter(c => c.published !== false)
  .sort((a, b) => (a.order || 99) - (b.order || 99));

const categoriesJsonPath = path.join(ROOT, 'assets', 'data', 'categories.json');
fs.writeFileSync(categoriesJsonPath, JSON.stringify(collections, null, 2), 'utf8');
console.log(`✓ categories.json — ${collections.length} collections`);

// ─── 4. Build occasions.json ──────────────────────────────────────────────────

const occasions = readJsonDir(OCCASIONS_DIR)
  .filter(o => o.published !== false)
  .sort((a, b) => (a.order || 99) - (b.order || 99));

const occasionsJsonPath = path.join(ROOT, 'assets', 'data', 'occasions.json');
fs.writeFileSync(occasionsJsonPath, JSON.stringify(occasions, null, 2), 'utf8');
console.log(`✓ occasions.json — ${occasions.length} occasions`);

console.log('\nBuild complete.');
